# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'checkout reference (sha/branch)'
        required: false
        type: string
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false # one failing job does not terminate the other jobs, so that we can see if a failure is reproducible or OS/JDK-specific
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        jdk: ['17', '21']
        experimental: [false]
        include:
          - os: 'ubuntu-latest'
            jdk: '24'
            experimental: true

    continue-on-error: ${{ matrix.experimental }} # failing experimental jobs does not fail the overall action
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION: ${{ matrix.jdk }}

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'temurin'
        cache:        'maven'

    - name: Compile
      run: mvn -B -DskipTests=true compile --file pom.xml

    - name: Test
      run: mvn -B verify --file pom.xml

    - name: Package
      run: mvn -B -DskipTests=true package --file pom.xml
